xen/privcmd: Fix build breakage due to PVH mmu changes.
We get:

drivers/xen/privcmd.c: In function ‘mmap_mfn_range’:
drivers/xen/privcmd.c:181: error: too few arguments to function ‘xen_remap_domain_mfn_range’
drivers/xen/privcmd.c: In function ‘mmap_batch_fn’:
drivers/xen/privcmd.c:270: error: too few arguments to function ‘xen_remap_domain_mfn_range’

This fixes it.

Signed-off-by: Konrad Rzeszutek Wilk <konrad.wilk@oracle.com>