efi: Fix compiler error introduced by moving of the code decleration.
The compiler error is :

arch/x86/platform/efi/efi.c:62: error: ‘efi_reserve_boot_services_generic’ undeclared here (not in a function

And declearing it before the use fixes the issue.

Signed-off-by: Konrad Rzeszutek Wilk <konrad.wilk@oracle.com>